[package]
name = "floatile-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "floatile"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
floatile-core = { workspace = true }
floatile-platform = { workspace = true }
floatile-runtime = { workspace = true }
floatile-store = { workspace = true }
floatile-ui-schema = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
wasmtime = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
floatile-plugin-api = { workspace = true }
